package com.smartcn.smartcndashboard.addtemplate;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "smartcn_templates")

public class TemplateModel {
	
	@DynamoDBHashKey(attributeName = "name")
	@DynamoDBAutoGeneratedKey
	private String name;
	private String owner;
	private String createdDate;
	private String lastChange;
	private String action;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getOwner() {
		return owner;
	}
	public void setOwner(String owner) {
		this.owner = owner;
	}
	public String getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}
	public String getLastChange() {
		return lastChange;
	}
	public void setLastChange(String lastChange) {
		this.lastChange = lastChange;
	}
	public String getAction() {
		return action;
	}
	public void setAction(String action) {
		this.action = action;
	}
	@Override
	public String toString() {
		return "TemplateModel [name=" + name + ", owner=" + owner + ", createdDate=" + createdDate + ", lastChange="
				+ lastChange + ", action=" + action + "]";
	}
	
}
