package com.smartcn.smartcndashboard.adminlogin;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "smartcn_admin_details")
public class AdminLoginModel {

	@DynamoDBHashKey(attributeName = "adminId")
	@DynamoDBAutoGeneratedKey
	private String adminId;
	private String name;
	private String password;
	private String email;
	private String department;
	private String createdOn;
	private String createdBy;
	public String getAdminId() {
		return adminId;
	}
	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	public String getCreatedOn() {
		return createdOn;
	}
	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	@Override
	public String toString() {
		return "AdminLoginModel [adminId=" + adminId + ", name=" + name + ", password=" + password + ", email=" + email
				+ ", department=" + department + ", createdOn=" + createdOn + ", createdBy=" + createdBy + "]";
	}

	

}
